# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7182af3c822e79889fd60dd9271e8b36df2fafd75da3a85a37084af1b00beca2ffee3f7250ec6590e992b6d8f9b65d189326389c4e8003416c90a18436880f99

test:
  secret_key_base: ff88c79e764c912b66f9c623db31d6c84fd5d81315d55edebb2e4b216b0cd10913d54e71d2dfb17e5bd65588a04782fb43e4b69ea1b41441c4f90f7eea8ab2b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
